version: "3.1"
services:
  redis:
    image: redis:alpine
    env_file:
    - .env
    container_name: qmserver-redis
  mysql:
    image: mysql:5.7
    container_name: qmserver-mysql
    working_dir: /application
    volumes:
    - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_DATABASE=${DB_NAME}
    - MYSQL_USER=${DB_USER}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
    - ${MYSQL_PORT}:3306
  webserver:
    image: nginx:alpine
    container_name: qmserver-webserver
    working_dir: /application
    volumes:
    - .:/application
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - ${SERVER_PORT}:80
  php-fpm:
    build: docker/php-fpm
    container_name: qmserver-php-fpm
    working_dir: /application
    volumes:
    - .:/application
    - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
    - ${PMA_PORT}:80
    links:
    - mysql:mysql
    environment:
    - PMA_HOST=${DB_HOST}

